name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          docker build -t ajinkya19/flask-app:latest .
          docker tag ajinkya19/flask-app:latest ajinkya19/flask-app:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ajinkya19/flask-app:latest
          docker push ajinkya19/flask-app:${{ github.sha }}

      - name: Deploy to Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

